const games = [
    { game : "CrossFire" },
    { game : "PlayerUnknown's Battlegrounds" },
    { game : "Minecraft" },
    { game : "Among Us" },
    { game : "Microsoft Solitaire" },
    { game : "Crazyracing Kartrider" },
    { game : "Fortnite" },
    { game : "RuneScape" },
    { game : "Rules of Survival" },
    { game : "Tetris" },
    { game : "World of Tanks" },
    { game : "League of Legends" },
    { game : "Dota 2" },
    { game : "World of Warcraft" },
    { game : "Scions of Fate" },
    { game : "Microsoft Solitaire Collection" },
    { game : "Call of Duty: Warzone" },
    { game : "Westward Journey Online II" },
    { game : "Rocket League" },
    { game : "Grand Theft Auto V" },
    { game : "Apex Legends" },
    { game : "Team Fortress 2" },
    { game : "Tom Clancy's Rainbow Six Siege" },
    { game : "Counter-Strike: Global Offensive" },
    { game : "FIFA 21" },
    { game : "Metal Slug Defense" },
    { game : "Street Fighter II" },
    { game : "Call of Duty: WWII" },
    { game : "Left 4 Dead 2" },
    { game : "Mafia II" },
    { game : "The Sims 4" },
    { game : "Payday 2" },
    { game : "Battlefield 4" },
    { game : "Call of Duty: Ghosts" },
    { game : "Free Realms" },
    { game : "Grand Theft Auto IV" },
    { game : "H1Z1" },
    { game : "Robocraft" },
    { game : "Lineage II" },
    { game : "Doom" },
    { game : "The Last of Us Remastered" },
    { game : "DC Universe Online" },
    { game : "Final Fantasy XIV" },
    { game : "Nexus: The Kingdom of the Winds" },
    { game : "Pac-Man" },
    { game : "Warframe" },
    { game : "Dragon Oath" },
    { game : "Hearthstone" },
    { game : "Overwatch" },
    { game : "The Witcher" },
]

module.exports = games